Repository rancher/rancher-docs, pull requests merged in 2023-12, with the labels that each got.

#1013 Port version-2.8 updates to latest (/docs)
  docs/api/api-reference.mdx
  docs/api/quickstart.md
  docs/api/workflows/projects.md
  docs/getting-started/installation-and-upgrade/installation-references/feature-flags.md
  docs/getting-started/installation-and-upgrade/installation-requirements/port-requirements.md
  docs/how-to-guides/new-user-guides/deploy-apps-across-clusters/fleet.md
  docs/how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/dynamically-provision-new-storage.md
  docs/how-to-guides/new-user-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/set-up-existing-storage.md
  docs/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
  docs/integrations-in-rancher/elemental/elemental.md
  docs/integrations-in-rancher/epinio/epinio.md
  docs/integrations-in-rancher/fleet/architecture.md
  docs/integrations-in-rancher/fleet/fleet.md
  docs/integrations-in-rancher/fleet/overview.md
  docs/integrations-in-rancher/fleet/use-fleet-behind-a-proxy.md
  docs/integrations-in-rancher/fleet/windows-support.md
  docs/integrations-in-rancher/harvester/harvester.md
  docs/integrations-in-rancher/harvester/overview.md
  docs/integrations-in-rancher/integrations-in-rancher.mdx
  docs/integrations-in-rancher/kubernetes-distributions/kubernetes-distributions.md
  docs/integrations-in-rancher/kubewarden/kubewarden.md
  docs/integrations-in-rancher/longhorn/longhorn.md
  docs/integrations-in-rancher/longhorn/overview.md
  docs/integrations-in-rancher/monitoring-and-alerting/built-in-dashboards.md
  docs/integrations-in-rancher/neuvector/neuvector.md
  docs/integrations-in-rancher/neuvector/overview.md
  docs/integrations-in-rancher/opni/opni.md
  docs/integrations-in-rancher/rancher-desktop.md
  docs/pages-for-subheaders/about-provisioning-drivers.md
  docs/pages-for-subheaders/create-kubernetes-persistent-storage.md
  docs/pages-for-subheaders/rancher-security.md
  docs/reference-guides/rancher-security/rancher-webhook-hardening.md
  docusaurus.config.js
  sidebars.js
Labels: MERGE ON RELEASE

#807 #773: Add steps to install Rancher Extensions in an air-gapped environment
  docs/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha.md
  docs/integrations-in-rancher/rancher-extensions.md
  versioned_docs/version-2.8/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha.md
  versioned_docs/version-2.8/integrations-in-rancher/rancher-extensions.md
Labels: next-release, MERGE ON RELEASE

#844 Add aws out of tree cloud provider install/upgrade docs
  docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon.md
  docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/migrate-to-out-of-tree-amazon.md
  docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/migrate-to-out-of-tree-vsphere.md
  docusaurus.config.js
  sidebars.js
  versioned_docs/version-2.8/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon.md
  versioned_docs/version-2.8/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/migrate-to-out-of-tree-amazon.md
  versioned_docs/version-2.8/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/migrate-to-out-of-tree-vsphere.md
  versioned_sidebars/version-2.8-sidebars.json
Labels: next-release, MERGE ON RELEASE

#1002 [DO NOT MERGE] Add 2.8 entry to versions table
  src/pages/versions.md
Labels: MERGE ON RELEASE

#1006 Update webhook version table
  docs/reference-guides/rancher-webhook.md
  versioned_docs/version-2.7/reference-guides/rancher-webhook.md
  versioned_docs/version-2.8/reference-guides/rancher-webhook.md
Labels: MERGE ON RELEASE

#1039 #1031 - Note about cloud credentials and admins
  docs/reference-guides/user-settings/manage-cloud-credentials.md
  versioned_docs/version-2.0-2.4/reference-guides/user-settings/manage-cloud-credentials.md
  versioned_docs/version-2.5/reference-guides/user-settings/manage-cloud-credentials.md
  versioned_docs/version-2.6/reference-guides/user-settings/manage-cloud-credentials.md
  versioned_docs/version-2.7/reference-guides/user-settings/manage-cloud-credentials.md
  versioned_docs/version-2.8/reference-guides/user-settings/manage-cloud-credentials.md
Labels: sync-versions
