Repository rancher/rancher-docs, pull requests merged in 2024-03, with the labels that each got.

#1138 Update CNI Table - 2.7.11
  shared-files/_cni-popularity.md
Labels: MERGE ON RELEASE

#1123 Adding webhook mapping for release 2.7.11
  versioned_docs/version-2.7/reference-guides/rancher-webhook.md
Labels: MERGE ON RELEASE

#1120 Add release 2.7.11 to version table
  src/pages/versions.md
Labels: MERGE ON RELEASE

#1133 Update csp-adapter version
  versioned_docs/version-2.7/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
Labels: next-release, MERGE ON RELEASE

#1152 Sync Docs Items - v2.7.11
  versioned_docs/version-2.7/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/migrate-to-an-out-of-tree-cloud-provider/migrate-to-out-of-tree-amazon.md
  versioned_docs/version-2.7/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/migrate-to-an-out-of-tree-cloud-provider/migrate-to-out-of-tree-vsphere.md
  versioned_docs/version-2.7/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon.md
  versioned_docs/version-2.7/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
  versioned_sidebars/version-2.7-sidebars.json
Labels: sync-versions

#1142 Add Weave deprecation notice
  docs/faq/container-network-interface-providers.md
  docs/reference-guides/cluster-configuration/rancher-server-configuration/rke1-cluster-configuration.md
  shared-files/_deprecation-weave.md
  src/theme/MDXComponents.js
  versioned_docs/version-2.7/faq/container-network-interface-providers.md
  versioned_docs/version-2.7/reference-guides/cluster-configuration/rancher-server-configuration/rke1-cluster-configuration.md
  versioned_docs/version-2.8/faq/container-network-interface-providers.md
  versioned_docs/version-2.8/reference-guides/cluster-configuration/rancher-server-configuration/rke1-cluster-configuration.md
Labels: MERGE ON RELEASE

#1130 #1128 Highlight expected behavior around permissions
  docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/authentication-config.md
  versioned_docs/version-2.0-2.4/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/about-authentication/about-authentication.md
  versioned_docs/version-2.5/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/about-authentication/about-authentication.md
  versioned_docs/version-2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/authentication-config.md
  versioned_docs/version-2.7/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/authentication-config.md
  versioned_docs/version-2.8/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/authentication-config.md
Labels: sync-versions

#1048 Update eks cluster configuration
  docs/reference-guides/cluster-configuration/rancher-server-configuration/eks-cluster-configuration.md
  versioned_docs/version-2.8/reference-guides/cluster-configuration/rancher-server-configuration/eks-cluster-configuration.md
Labels: DO NOT MERGE, next-release, sync-versions

#1166 Warn users that Rancher in Docker isn't supported
  docs/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/rancher-on-a-single-node-with-docker.md
  versioned_docs/version-2.0-2.4/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/rancher-on-a-single-node-with-docker.md
  versioned_docs/version-2.5/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/rancher-on-a-single-node-with-docker.md
  versioned_docs/version-2.6/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/rancher-on-a-single-node-with-docker.md
  versioned_docs/version-2.7/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/rancher-on-a-single-node-with-docker.md
  versioned_docs/version-2.8/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/rancher-on-a-single-node-with-docker.md
Labels: sync-versions

#1179 Update CNI Table - 2.8.3
  shared-files/_cni-popularity.md
Labels: MERGE ON RELEASE

#1191 Update trobleshooting tips regarding leader election
  docs/troubleshooting/other-troubleshooting-tips/rancher-ha.md
  versioned_docs/version-2.8/troubleshooting/other-troubleshooting-tips/rancher-ha.md
Labels: MERGE ON RELEASE

#1180 Adding Webhook Mapping for Release 2.8.3
  docs/reference-guides/rancher-webhook.md
  versioned_docs/version-2.8/reference-guides/rancher-webhook.md
Labels: MERGE ON RELEASE

#1178 Update Docs Versions Table for v2.8.3
  src/pages/versions.md
Labels: MERGE ON RELEASE

#1200 Updating Versions Table for 2.7.12
  src/pages/versions.md
Labels: MERGE ON RELEASE

#1181 Adding Webhook Mapping for Release 2.7.12
  versioned_docs/version-2.7/reference-guides/rancher-webhook.md
Labels: MERGE ON RELEASE
