Repository rancher/rancher-docs, pull requests merged in 2025-07, with the labels that each got.

#1850 Add additional tasks to release checklist
  .github/ISSUE_TEMPLATE/release-maintenance-checklist.md
Labels: port/community-product

#1852 Require API Aggregation
  docs/api/extension-apiserver.md
Labels: MERGE ON RELEASE

#1860 Add UpdatePSA for Project level instructions
  docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles.md
Labels: port/community-product

#1822 Remove references to deprecated resourceset
  docs/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher.md
  docs/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/backup-restore-and-disaster-recovery.md
  docs/reference-guides/backup-restore-configuration/backup-configuration.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/back-up-rancher.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/backup-restore-and-disaster-recovery.md
  versioned_docs/version-2.12/reference-guides/backup-restore-configuration/backup-configuration.md
Labels: port/community-product

#1834 Add new project scoped secret documentation
  docs/how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md
Labels: port/community-product

#1840 Add amazon cognito
  docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-amazon-cognito.md
  sidebars.js
  versioned_docs/version-2.12/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-amazon-cognito.md
  versioned_sidebars/version-2.12-sidebars.json
Labels: port/community-product

#1841 Clarify the expected format of `NO_PROXY`
  docs/getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-kubernetes.md
  docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
  docs/integrations-in-rancher/fleet/use-fleet-behind-a-proxy.md
  docs/reference-guides/single-node-rancher-in-docker/http-proxy-configuration.md
  versioned_docs/version-2.10/getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-kubernetes.md
  versioned_docs/version-2.10/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
  versioned_docs/version-2.10/integrations-in-rancher/fleet/use-fleet-behind-a-proxy.md
  versioned_docs/version-2.10/reference-guides/single-node-rancher-in-docker/http-proxy-configuration.md
  versioned_docs/version-2.11/getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-kubernetes.md
  versioned_docs/version-2.11/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
  versioned_docs/version-2.11/integrations-in-rancher/fleet/use-fleet-behind-a-proxy.md
  versioned_docs/version-2.11/reference-guides/single-node-rancher-in-docker/http-proxy-configuration.md
  versioned_docs/version-2.12/getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-kubernetes.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
  versioned_docs/version-2.12/integrations-in-rancher/fleet/use-fleet-behind-a-proxy.md
  versioned_docs/version-2.12/reference-guides/single-node-rancher-in-docker/http-proxy-configuration.md
  versioned_docs/version-2.9/getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-kubernetes.md
  versioned_docs/version-2.9/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
  versioned_docs/version-2.9/integrations-in-rancher/fleet/use-fleet-behind-a-proxy.md
Labels: port/community-product

#1844 OIDC provider doc
  docs/how-to-guides/advanced-user-guides/configure-oidc-provider.md
  sidebars.js
  versioned_docs/version-2.12/how-to-guides/advanced-user-guides/configure-oidc-provider.md
  versioned_sidebars/version-2.12-sidebars.json
Labels: port/community-product

#1885 Remove RKE1 references: contribute-to-rancher
  docs/contribute-to-rancher.md
  i18n/zh/docusaurus-plugin-content-docs/current/contribute-to-rancher.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/contribute-to-rancher.md
  versioned_docs/version-2.12/contribute-to-rancher.md
Labels: port/community-product

#1839 Add Tokens example workflows page
  docs/api/workflows/tokens.md
  sidebars.js
  versioned_docs/version-2.12/api/workflows/tokens.md
  versioned_sidebars/version-2.12-sidebars.json
Labels: port/community-product

#1866 Add documentation for new GCE Node Driver
  docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/about-provisioning-drivers.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-google-compute-engine-cluster.md
  docs/reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/google-gce.md
  sidebars.js
  versioned_docs/version-2.12/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/about-provisioning-drivers.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-google-compute-engine-cluster.md
  versioned_docs/version-2.12/reference-guides/cluster-configuration/downstream-cluster-configuration/machine-configuration/google-gce.md
  versioned_sidebars/version-2.12-sidebars.json
Labels: port/community-product

#1899 Fix Kubeconfigs example workflows page
  docs/api/workflows/kubeconfigs.md
  versioned_docs/version-2.12/api/workflows/kubeconfigs.md
Labels: port/community-product

#1893 Remove RKE1 references: Reference Guides pages
  docs/reference-guides/best-practices/rancher-managed-clusters/disconnected-clusters.md
  docs/reference-guides/best-practices/rancher-managed-clusters/logging-best-practices.md
  docs/reference-guides/best-practices/rancher-server/tips-for-running-rancher.md
  docs/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
  docs/reference-guides/cluster-configuration/cluster-configuration.md
  docs/reference-guides/cluster-configuration/rancher-server-configuration/rancher-server-configuration.md
  docs/reference-guides/rancher-manager-architecture/architecture-recommendations.md
  docs/reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.md
  docs/reference-guides/rancher-security/hardening-guides/hardening-guides.md
  docs/reference-guides/rancher-security/rancher-security-best-practices.md
  docs/reference-guides/rancher-security/rancher-security.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/best-practices/rancher-managed-clusters/disconnected-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/best-practices/rancher-managed-clusters/logging-best-practices.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/best-practices/rancher-server/tips-for-running-rancher.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/cluster-configuration/cluster-configuration.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/cluster-configuration/rancher-server-configuration/rancher-server-configuration.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/rancher-manager-architecture/architecture-recommendations.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/rancher-security/hardening-guides/hardening-guides.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/rancher-security/rancher-security.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/best-practices/rancher-managed-clusters/disconnected-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/best-practices/rancher-managed-clusters/logging-best-practices.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/best-practices/rancher-server/tips-for-running-rancher.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/cluster-configuration/cluster-configuration.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/cluster-configuration/rancher-server-configuration/rancher-server-configuration.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/rancher-manager-architecture/architecture-recommendations.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/rancher-security/hardening-guides/hardening-guides.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/rancher-security/rancher-security.md
  versioned_docs/version-2.12/reference-guides/best-practices/rancher-managed-clusters/disconnected-clusters.md
  versioned_docs/version-2.12/reference-guides/best-practices/rancher-managed-clusters/logging-best-practices.md
  versioned_docs/version-2.12/reference-guides/best-practices/rancher-server/tips-for-running-rancher.md
  versioned_docs/version-2.12/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
  versioned_docs/version-2.12/reference-guides/cluster-configuration/cluster-configuration.md
  versioned_docs/version-2.12/reference-guides/cluster-configuration/rancher-server-configuration/rancher-server-configuration.md
  versioned_docs/version-2.12/reference-guides/rancher-manager-architecture/architecture-recommendations.md
  versioned_docs/version-2.12/reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters.md
  versioned_docs/version-2.12/reference-guides/rancher-security/hardening-guides/hardening-guides.md
  versioned_docs/version-2.12/reference-guides/rancher-security/rancher-security-best-practices.md
  versioned_docs/version-2.12/reference-guides/rancher-security/rancher-security.md
Labels: port/community-product

#1906 Update API reference JSON for v2.12.0
  docs/api/api-reference.mdx
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-docs/current/api/api-reference.mdx
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/api/api-reference.mdx
  openapi/swagger-v2.12.json
  versioned_docs/version-2.12/api/api-reference.mdx
Labels: port/community-product

#1909 Remove RKE1 references: Reference Guides pages (pt2)
  .github/workflows/deploy.yml
  docs/reference-guides/cluster-configuration/downstream-cluster-configuration/downstream-cluster-configuration.md
  docs/reference-guides/kubernetes-concepts.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/cluster-configuration/downstream-cluster-configuration/downstream-cluster-configuration.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/kubernetes-concepts.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/cluster-configuration/downstream-cluster-configuration/downstream-cluster-configuration.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/kubernetes-concepts.md
  versioned_docs/version-2.12/reference-guides/cluster-configuration/downstream-cluster-configuration/downstream-cluster-configuration.md
  versioned_docs/version-2.12/reference-guides/kubernetes-concepts.md
Labels: port/community-product

#1907 Document Notification Center
  docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/notification-center.md
  sidebars.js
  versioned_docs/version-2.12/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/notification-center.md
  versioned_sidebars/version-2.12-sidebars.json
Labels: port/community-product

#1912 [v2.12] Remove hardening guides and refactor CIS profiles
  docs/how-to-guides/advanced-user-guides/compliance-scan-guides/configure-alerts-for-periodic-scan-on-a-schedule.md
  docs/how-to-guides/advanced-user-guides/compliance-scan-guides/run-a-scan-periodically-on-a-schedule.md
  docs/how-to-guides/advanced-user-guides/compliance-scan-guides/run-a-scan.md
  docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates.md
  docs/integrations-in-rancher/compliance-scans/compliance-scans.md
  docs/reference-guides/rancher-security/hardening-guides/hardening-guides.md
  docs/reference-guides/rancher-security/hardening-guides/k3s-hardening-guide/k3s-hardening-guide.md
  docs/reference-guides/rancher-security/hardening-guides/k3s-hardening-guide/k3s-self-assessment-guide-with-cis-v1.7-k8s-v1.25-v1.26-v1.27.md
  docs/reference-guides/rancher-security/hardening-guides/rke1-hardening-guide/rke1-hardening-guide.md
  docs/reference-guides/rancher-security/hardening-guides/rke1-hardening-guide/rke1-self-assessment-guide-with-cis-v1.7-k8s-v1.25-v1.26-v1.27.md
  docs/reference-guides/rancher-security/hardening-guides/rke2-hardening-guide/rke2-hardening-guide.md
  docs/reference-guides/rancher-security/hardening-guides/rke2-hardening-guide/rke2-self-assessment-guide-with-cis-v1.7-k8s-v1.25-v1.26-v1.27.md
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/rancher-security/hardening-guides/rke1-hardening-guide/rke1-hardening-guide.md
  i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/rancher-security/hardening-guides/rke1-hardening-guide/rke1-self-assessment-guide-with-cis-v1.7-k8s-v1.25-v1.26-v1.27.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/rancher-security/hardening-guides/rke1-hardening-guide/rke1-hardening-guide.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/reference-guides/rancher-security/hardening-guides/rke1-hardening-guide/rke1-self-assessment-guide-with-cis-v1.7-k8s-v1.25-v1.26-v1.27.md
  sidebars.js
  versioned_docs/version-2.12/how-to-guides/advanced-user-guides/compliance-scan-guides/configure-alerts-for-periodic-scan-on-a-schedule.md
  versioned_docs/version-2.12/how-to-guides/advanced-user-guides/compliance-scan-guides/run-a-scan-periodically-on-a-schedule.md
  versioned_docs/version-2.12/how-to-guides/advanced-user-guides/compliance-scan-guides/run-a-scan.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates.md
  versioned_docs/version-2.12/integrations-in-rancher/compliance-scans/compliance-scans.md
  versioned_docs/version-2.12/reference-guides/rancher-security/hardening-guides/hardening-guides.md
  versioned_docs/version-2.12/reference-guides/rancher-security/hardening-guides/k3s-hardening-guide/k3s-hardening-guide.md
  versioned_docs/version-2.12/reference-guides/rancher-security/hardening-guides/k3s-hardening-guide/k3s-self-assessment-guide-with-cis-v1.7-k8s-v1.25-v1.26-v1.27.md
  versioned_docs/version-2.12/reference-guides/rancher-security/hardening-guides/rke1-hardening-guide/rke1-hardening-guide.md
  versioned_docs/version-2.12/reference-guides/rancher-security/hardening-guides/rke1-hardening-guide/rke1-self-assessment-guide-with-cis-v1.7-k8s-v1.25-v1.26-v1.27.md
  versioned_docs/version-2.12/reference-guides/rancher-security/hardening-guides/rke2-hardening-guide/rke2-hardening-guide.md
  versioned_docs/version-2.12/reference-guides/rancher-security/hardening-guides/rke2-hardening-guide/rke2-self-assessment-guide-with-cis-v1.7-k8s-v1.25-v1.26-v1.27.md
  versioned_sidebars/version-2.12-sidebars.json
Labels: port/community-product

#1888 [2.12.0] Update `ui-sql-cache` & Server-Side Pagination Content
  docs/getting-started/installation-and-upgrade/installation-references/feature-flags.md
  docs/how-to-guides/advanced-user-guides/enable-experimental-features/ui-server-side-pagination.md
  docs/how-to-guides/advanced-user-guides/ui-server-side-pagination.md
  sidebars.js
  versioned_docs/version-2.12/getting-started/installation-and-upgrade/installation-references/feature-flags.md
  versioned_docs/version-2.12/how-to-guides/advanced-user-guides/enable-experimental-features/ui-server-side-pagination.md
  versioned_docs/version-2.12/how-to-guides/advanced-user-guides/ui-server-side-pagination.md
  versioned_sidebars/version-2.12-sidebars.json
Labels: port/community-product

#1921 Remove RKE1: /integrations-in-rancher pages (Harvester)
  docs/integrations-in-rancher/harvester/overview.md
  i18n/zh/docusaurus-plugin-content-docs/current/integrations-in-rancher/harvester/overview.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/integrations-in-rancher/harvester/overview.md
  versioned_docs/version-2.12/integrations-in-rancher/harvester/overview.md
Labels: port/community-product

#1924 Remove RKE1 references: use-new-nodes-in-an-infra-provider/<providers>
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-digitalocean-cluster.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-google-compute-engine-cluster.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-an-amazon-ec2-cluster.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-an-azure-cluster.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/nutanix/nutanix.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/create-a-vm-template.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/create-credentials.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/provision-kubernetes-clusters-in-vsphere.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/shutdown-vm.md
  docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/vsphere.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-digitalocean-cluster.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-google-compute-engine-cluster.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-an-amazon-ec2-cluster.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-an-azure-cluster.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/nutanix/nutanix.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/create-a-vm-template.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/create-credentials.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/provision-kubernetes-clusters-in-vsphere.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/shutdown-vm.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/vsphere.md
Labels: port/community-product

#1930 Remove RKE1 references: use-kubectl-and-kubeconfig
  docs/how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.md
  i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/manage-clusters/access-clusters/use-kubectl-and-kubeconfig.md
Labels: port/community-product

#1928 Remove RKE1 references: rotate certs and encryption keys
  docs/how-to-guides/new-user-guides/manage-clusters/rotate-certificates.md
  docs/how-to-guides/new-user-guides/manage-clusters/rotate-encryption-key.md
  i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/new-user-guides/manage-clusters/rotate-certificates.md
  i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/new-user-guides/manage-clusters/rotate-encryption-key.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/how-to-guides/new-user-guides/manage-clusters/rotate-certificates.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.12/how-to-guides/new-user-guides/manage-clusters/rotate-encryption-key.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/manage-clusters/rotate-certificates.md
  versioned_docs/version-2.12/how-to-guides/new-user-guides/manage-clusters/rotate-encryption-key.md
Labels: port/community-product

#1903 Merge release branch v2.11.4 into main
  i18n/zh/docusaurus-plugin-content-docs/version-2.11/faq/deprecated-features.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.11/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.11/reference-guides/rancher-webhook.md
  src/pages/versions.md
  versioned_docs/version-2.11/faq/deprecated-features.md
  versioned_docs/version-2.11/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
  versioned_docs/version-2.11/reference-guides/rancher-webhook.md
Labels: DO NOT MERGE

#1902 Merge release branch v2.10.8 into main
  i18n/zh/docusaurus-plugin-content-docs/version-2.10/faq/deprecated-features.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.10/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
  i18n/zh/docusaurus-plugin-content-docs/version-2.10/reference-guides/rancher-webhook.md
  src/pages/versions.md
  versioned_docs/version-2.10/faq/deprecated-features.md
  versioned_docs/version-2.10/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
  versioned_docs/version-2.10/reference-guides/rancher-webhook.md
Labels: DO NOT MERGE
